HOW TO WRITE CSV FILE

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('D:\\ML\\employee_information.csv')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,2020-06-15,60000,"123 Main St, NY"
1,102,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,2019-08-21,75000,"456 Oak St, CA"
2,103,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2021-02-10,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,2018-11-05,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,2022-07-19,72000,"654 Elm St, WA"

In [8]:
df=pd.read_csv('D:\\ML\\employee_information.csv',header=1)
df

,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,2020-06-15,60000,"123 Main St, NY"
0,102,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,2019-08-21,75000,"456 Oak St, CA"
1,103,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2021-02-10,68000,"789 Pine St, TX"
2,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,2018-11-05,55000,"321 Maple St, FL"
3,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,2022-07-19,72000,"654 Elm St, WA"

In [30]:
df=pd.read_csv('D:\\ML\\employee_information.csv',names=[1,2,3])
df

                                                                                              1  \
NaN   NaN           NaN       NaN         NaN                   NaN          NaN            NaN
101.0 Alice Johnson HR        Manager     alice.j@example.com   123-456-7890 6/15/2020  60000.0
102.0 Bob Smith     IT        Developer   bob.s@example.com     234-567-8901 8/21/2019  75000.0
103.0 Charlie Brown Finance   Analyst     charlie.b@example.com 345-678-9012 2/10/2021  68000.0
104.0 David Lee     Marketing Coordinator david.l@example.com   456-789-0123 11/5/2018  55000.0
105.0 Eva Adams     Sales     Executive   eva.a@example.com     567-890-1234 7/19/2022  72000.0
NaN   NaN           NaN       NaN         NaN                   NaN          NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN
                                                                             NaN            NaN

                                                                                                       2  \
NaN   NaN           NaN       NaN         NaN                   NaN          NaN                     NaN
101.0 Alice Johnson HR        Manager     alice.j@example.com   123-456-7890 6/15/2020   123 Main St, NY
102.0 Bob Smith     IT        Developer   bob.s@example.com     234-567-8901 8/21/2019    456 Oak St, CA
103.0 Charlie Brown Finance   Analyst     charlie.b@example.com 345-678-9012 2/10/2021   789 Pine St, TX
104.0 David Lee     Marketing Coordinator david.l@example.com   456-789-0123 11/5/2018  321 Maple St, FL
105.0 Eva Adams     Sales     Executive   eva.a@example.com     567-890-1234 7/19/2022    654 Elm St, WA
NaN   NaN           NaN       NaN         NaN                   NaN          NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN
                                                                             NaN                     NaN

                                                                                         3
NaN   NaN           NaN       NaN         NaN                   NaN          NaN       NaN
101.0 Alice Johnson HR        Manager     alice.j@example.com   123-456-7890 6/15/2020 NaN
102.0 Bob Smith     IT        Developer   bob.s@example.com     234-567-8901 8/21/2019 NaN
103.0 Charlie Brown Finance   Analyst     charlie.b@example.com 345-678-9012 2/10/2021 NaN
104.0 David Lee     Marketing Coordinator david.l@example.com   456-789-0123 11/5/2018 NaN
105.0 Eva Adams     Sales     Executive   eva.a@example.com     567-890-1234 7/19/2022 NaN
NaN   NaN           NaN       NaN         NaN                   NaN          NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN
                                                                             NaN       NaN

In [28]:
pd.read_csv('D:\\ML\\employee_information.csv',header=None,prefix='column')

TypeError: read_csv() got an unexpected keyword argument 'prefix'

In [43]:
df=pd.read_csv('D:\\ML\\employee_information.csv')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address,Unnamed: 9
0,101.0,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000.0,"123 Main St, NY",NaN
1,102.0,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000.0,"456 Oak St, CA",NaN
2,103.0,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2/10/2021,68000.0,"789 Pine St, TX",NaN
3,104.0,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,11/5/2018,55000.0,"321 Maple St, FL",NaN
4,105.0,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000.0,"654 Elm St, WA",NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df.head()

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address,Unnamed: 9
0,101.0,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000.0,"123 Main St, NY",NaN
1,102.0,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000.0,"456 Oak St, CA",NaN
2,103.0,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2/10/2021,68000.0,"789 Pine St, TX",NaN
3,104.0,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,11/5/2018,55000.0,"321 Maple St, FL",NaN
4,105.0,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000.0,"654 Elm St, WA",NaN

In [41]:
df.tail()

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address,Unnamed: 9
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',dtype={'Employee ID':'float64'})
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101.0,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000.0,"123 Main St, NY"
1,102.0,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000.0,"456 Oak St, CA"
2,103.0,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2/10/2021,68000.0,"789 Pine St, TX"
3,104.0,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,11/5/2018,55000.0,"321 Maple St, FL"
4,105.0,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000.0,"654 Elm St, WA"

In [49]:
df = df.dropna(how='all')  # Removes rows where all values are NaN
df = df.dropna(axis=1, how='all')  # Removes empty columns

In [51]:
df.dropna(how='all', inplace=True)
df.dropna(axis=1, how='all', inplace=True)
df.reset_index(drop=True, inplace=True)

In [55]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',dtype={'Employee ID':'float64','Salary':'int32'})
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101.0,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102.0,Bob Smith,IT,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103.0,Charlie Brown,Finance,Analyst,charlie.b@example.com,345-678-9012,2/10/2021,68000,"789 Pine St, TX"
3,104.0,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,11/5/2018,55000,"321 Maple St, FL"
4,105.0,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"