In [5]:
import pandas as pd

In [2]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,no values,72000,"654 Elm St, WA"

In [3]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,no values,72000,"654 Elm St, WA"

In [11]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',na_values='no values')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,NaN,72000,"654 Elm St, WA"

In [15]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',na_values= {'Date of Hire':'no values'})
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,NaN,72000,"654 Elm St, WA"

In [17]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',keep_default_na=False)
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,,Analyst,charlie.b@example.com,345-678-9012,,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,no values,72000,"654 Elm St, WA"

In [19]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv')
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,6/14/2020,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,6/15/2020,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,6/15/2020,72000,"654 Elm St, WA"

In [21]:
df.isnull()

,Employee ID,Name,Department,Position,Email,Phone Number,Date,Salary,Address
0,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [23]:
df.isnull().sum()

Employee ID     0
Name            0
Department      2
Position        0
Email           0
Phone Number    0
Date            0
Salary          0
Address         0
dtype: int64

In [25]:
df.isnull().sum().sum()

2

In [27]:
df.notnull()

,Employee ID,Name,Department,Position,Email,Phone Number,Date,Salary,Address
0,True,True,True,True,True,True,True,True,True
1,True,True,False,True,True,True,True,True,True
2,True,True,False,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True

In [29]:
df.notnull().sum()

Employee ID     5
Name            5
Department      3
Position        5
Email           5
Phone Number    5
Date            5
Salary          5
Address         5
dtype: int64

In [31]:
df.notnull().sum().sum()

43

In [33]:
import numpy as np
sr=pd.Series([1,2,3,np.nan,4,np.NAN])
sr

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
5    NaN
dtype: float64

In [35]:
sr.isnull()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool