# How to create python pandas data frame

In [2]:
import pandas as pd

In [3]:
list=['a','b','c','d']
print(list)

['a', 'b', 'c', 'd']

In [4]:
var1=pd.DataFrame(list)
print(var1)

   0
0  a
1  b
2  c
3  d

In [5]:
var1

   0
0  a
1  b
2  c
3  d

In [6]:
list2=[['a','b','c','d'],['e','f','g','h'],['i','j','k','l']]
print(list2)

[['a', 'b', 'c', 'd'], ['e', 'f', 'g', 'h'], ['i', 'j', 'k', 'l']]

In [7]:
var2=pd.DataFrame(list2)
print(var2)

   0  1  2  3
0  a  b  c  d
1  e  f  g  h
2  i  j  k  l

In [8]:
var2

   0  1  2  3
0  a  b  c  d
1  e  f  g  h
2  i  j  k  l

In [9]:
dict1={'ID' : [0,1,2,3,4],'NUMBER' :  [89,76,99,65,-66]}
print(dict1)

{'ID': [0, 1, 2, 3, 4], 'NUMBER': [89, 76, 99, 65, -66]}

In [10]:
var3=pd.DataFrame(dict1)
print(var3)

   ID  NUMBER
0   0      89
1   1      76
2   2      99
3   3      65
4   4     -66

In [11]:
var3

   ID  NUMBER
0   0      89
1   1      76
2   2      99
3   3      65
4   4     -66

In [12]:
dict2=[{'ID' :1,'NUMBER' :78},{'ID' :2},{'ID' :3,'NUMBER' :70},{'ID' :4,'NUMBER' :90},{'ID' :8}]
var4=pd.DataFrame(dict2)
print(var4)

   ID  NUMBER
0   1    78.0
1   2     NaN
2   3    70.0
3   4    90.0
4   8     NaN

In [13]:
var4

   ID  NUMBER
0   1    78.0
1   2     NaN
2   3    70.0
3   4    90.0
4   8     NaN

In [14]:
emt_df=pd.DataFrame()
print(emt_df)

Empty DataFrame
Columns: []
Index: []

In [35]:
dict_2={'Id' :[1,2,3,4], 'Name' :["afrin","inaya","raya","subah"]}
print(dict_2)

{'Id': [1, 2, 3, 4], 'Name': ['afrin', 'inaya', 'raya', 'subah']}

In [37]:
dict_2

{'Id': [1, 2, 3, 4], 'Name': ['afrin', 'inaya', 'raya', 'subah']}

In [39]:
df3=pd.DataFrame(dict_2)
print(df3)

   Id   Name
0   1  afrin
1   2  inaya
2   3   raya
3   4  subah

In [41]:
df3

   Id   Name
0   1  afrin
1   2  inaya
2   3   raya
3   4  subah