In [1]:
import pandas as pd

In [2]:
pd.read_csv('D:\\ML\\cleaned_employee_information.csv')

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [3]:
import os

In [4]:
print (os.getcwd())

C:\Users\88017

In [16]:
pd.read_csv('D:\\ML\\cleaned_employee_information.csv')

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [ ]:
import pandas as pd

In [18]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv') 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [20]:
type(df)

pandas.core.frame.DataFrame

In [22]:
df.columns

Index(['Employee ID', 'Name', 'Department', 'Position', 'Email',
       'Phone Number', 'Date of Hire', 'Salary', 'Address'],
      dtype='object')

In [26]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', nrows=1) 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"

In [30]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', nrows=3) 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"

In [32]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', usecols=[0]) 
df

   Employee ID
0          101
1          102
2          103
3          104
4          105

In [34]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', usecols=[2]) 
df

  Department
0         HR
1        NaN
2        NaN
3  Marketing
4      Sales

In [36]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', usecols=[2,5]) 
df

  Department  Phone Number
0         HR  123-456-7890
1        NaN  234-567-8901
2        NaN  345-678-9012
3  Marketing  456-789-0123
4      Sales  567-890-1234

In [38]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', skiprows=1) 
df

,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
0,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
1,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
2,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
3,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [40]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', skiprows=[1,2,3]) 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
1,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [42]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [48]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', index_col='Name') 
df

,Employee ID,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
Name,,,,,,,,
Alice Johnson,101,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
Bob Smith,102,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
Charlie Brown,103,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
David Lee,104,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
Eva Adams,105,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [50]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', header=1) 
df

,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
0,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
1,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
2,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
3,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [52]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv') 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [54]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', header=None) 
df

,0,1,2,3,4,5,6,7,8
0,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
1,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
2,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
3,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
4,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
5,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [56]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',header=None, prefix='Columns') 
df

TypeError: read_csv() got an unexpected keyword argument 'prefix'

In [62]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv', names=['A','B','C','D','E','F','G','H']) 
df

,A,B,C,D,E,F,G,H
Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [64]:
df.head()

,A,B,C,D,E,F,G,H
Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"

In [66]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv') 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [68]:
df.head()

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [70]:
df.head(1)

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"

In [72]:
df.tail()

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [74]:
df.tail(2)

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
3,104,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"

In [76]:
df=pd.read_csv('D:\\ML\\cleaned_employee_information.csv',dtype={'Employee ID': 'float64'}) 
df

,Employee ID,Name,Department,Position,Email,Phone Number,Date of Hire,Salary,Address
0,101.0,Alice Johnson,HR,Manager,alice.j@example.com,123-456-7890,6/15/2020,60000,"123 Main St, NY"
1,102.0,Bob Smith,NaN,Developer,bob.s@example.com,234-567-8901,8/21/2019,75000,"456 Oak St, CA"
2,103.0,Charlie Brown,NaN,Analyst,charlie.b@example.com,345-678-9012,NaN,68000,"789 Pine St, TX"
3,104.0,David Lee,Marketing,Coordinator,david.l@example.com,456-789-0123,NaN,55000,"321 Maple St, FL"
4,105.0,Eva Adams,Sales,Executive,eva.a@example.com,567-890-1234,7/19/2022,72000,"654 Elm St, WA"